use_frameworks!

target 'Files_Example' do
  pod 'Files', :path => '../'

  target 'Files_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
